language: csharp
solution: UniConvert.sln

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nsis nsis-common

script:
  - xbuild /p:Configuration=Release UniConvert.sln
  - /usr/bin/makensis nsis/build.nsi